# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z6dThH52Y3DIOkXswC0QjD3bTSaXlS1U
"""

import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

validation_datagen = ImageDataGenerator(rescale=1.0 / 255.0)
test_datagen = ImageDataGenerator(rescale=1.0 / 255.0)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=64,
    class_mode='categorical'
)

validation_generator = validation_datagen.flow_from_directory(
    validation_dir,
    target_size=(224, 224),
    batch_size=64,
    class_mode='categorical'
)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=64,
    class_mode='categorical'
)

# Fungsi untuk menampilkan beberapa contoh gambar
def show_images(image_generator, num_images=5):
    # Mendapatkan nama kategori
    class_names = list(image_generator.class_indices.keys())
    
    # Mendapatkan beberapa contoh gambar
    images, labels = next(image_generator)
    
    # Menampilkan gambar dan labelnya
    fig, axes = plt.subplots(1, num_images, figsize=(20, 20))
    axes = axes.flatten()
    for i in range(num_images):
        img = images[i]
        label = labels[i]
        class_name = class_names[np.argmax(label)]
        axes[i].imshow(img)
        axes[i].set_title(class_name)
        axes[i].axis('off')
    plt.tight_layout()
    plt.show()

# Memanggil fungsi show_images untuk train_generator
show_images(train_generator)

# Memanggil fungsi show_images untuk validation_generator
show_images(validation_generator)

# Memanggil fungsi show_images untuk test_generator
show_images(test_generator)
